name: bert_classification
params:
  base_model: ${bert_base_model}
  use_subj_end: false
  cls_loss: binary_cross_entropy
  cls_lambda: 1.0
  mean_num_classes: ${mean_num_classes}
  mean_loss: cross_entropy
  mean_lambda: 1.0
  std_num_classes: ${std_num_classes}
  std_loss: cross_entropy
  std_lambda: 1.0
  bert_finetune: false
